version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data: