// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckUserNameExists(ctx context.Context, username string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolesForUser(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
